### ISSUE TITLE
Getting error: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by Nedomas** [askovpen/node-fidonet-mailer-binkp-crypt#5]
Hello!

I've just tried to use a few github repo downloaders and it seems that all of them use this library and crash. I was wondering if the last fix could have broken it?

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/domas/Developer/closeheat/cli/node_modules/download-github-repo/node_modules/download/node_modules/decompress/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build/Release/crypt.no
de: undefined symbol: node_module_register
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/domas/Developer/closeheat/cli/node_modules/download-github-repo/node_modules/download/node_modules/decompress/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/fido
net-mailer-binkp-crypt.js:1:74)
```

**Comment by askovpen** [comment]
try again. with version 0.0.29
