### ISSUE TITLE
Requirement for `g++` causing is causing install failure

### ISSUE THREAD

**Issue by misterbrownlee** [askovpen/node-fidonet-mailer-binkp-crypt#6]
Hi -

This project is a dependency of `karma-sauce-launcher`, and a recent change you published is now causing failures on Linux systems (like our CI server).

Here's the error:

```
> fidonet-mailer-binkp-crypt@0.0.29 install /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
> node-gyp configure build

make: Entering directory `/apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build'
  CXX(target) Release/obj.target/crypt/crypt.o
make: g++: Command not found
make: *** [Release/obj.target/crypt/crypt.o] Error 127
make: Leaving directory `/apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/qabasel/tools/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-504.1.3.el6.x86_64
gyp ERR! command "node" "/home/qabasel/tools/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! fidonet-mailer-binkp-crypt@0.0.29 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.29 install script.
npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-504.1.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-504.1.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html
npm ERR! fstream_path /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/qabasel/tools/nodejs/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/npm-debug.log
npm ERR! not ok code 0
```

The dependency trace looks like this:

```
            "sauce-connect-launcher": {
              "version": "0.6.1",
              "from": "sauce-connect-launcher@>=0.6.0 <0.7.0",
              "resolved": "https://registry.npmjs.org/sauce-connect-launcher/-/sauce-connect-launcher-0.6.1.tgz",
              "dependencies": {
                "lodash": {
                  "version": "2.4.1",
                  "from": "lodash@2.4.1",
                  "resolved": "https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz"
                },
                "async": {
                  "version": "0.9.0",
                  "from": "async@>=0.9.0 <0.10.0",
                  "resolved": "https://registry.npmjs.org/async/-/async-0.9.0.tgz"
                },
                "adm-zip": {
                  "version": "0.4.5",
                  "from": "adm-zip@>=0.4.3 <0.5.0",
                  "resolved": "https://registry.npmjs.org/adm-zip/-/adm-zip-0.4.5.tgz",
                  "dependencies": {
                    "fidonet-mailer-binkp-crypt": {
                      "version": "0.0.25",
                      "from": "fidonet-mailer-binkp-crypt@>0.0.20",
                      "resolved": "https://registry.npmjs.org/fidonet-mailer-binkp-crypt/-/fidonet-mailer-binkp-crypt-0.0.25.tgz",
                      "dependencies": {
                        "nan": {
                          "version": "1.6.2",
                          "from": "nan@>0.0.0",
                          "resolved": "https://registry.npmjs.org/nan/-/nan-1.6.2.tgz"
                        }
                      }
                    }
                  }
                },
```

We're going to try and work around with npm-shrinkwrap, but thought I would share this here since it's likely causing people besides us a bit of a headache.

**Comment by jdevost** [comment]
We have a similar issue. Here's the error: 

```
> fidonet-mailer-binkp-crypt@0.0.29 install /usr/local/lib/node_modules/intern/node_modules/digdug/node_modules/decompress/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
> node-gyp configure build

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:103:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:42:11
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:25)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/intern/node_modules/digdug/node_modules/decompress/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! fidonet-mailer-binkp-crypt@0.0.29 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.29 install script.
npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "intern@2.2.2"
npm ERR! cwd /opt/node_app
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/node_app/npm-debug.log
npm ERR! not ok code 0
```

**Comment by blaiprat** [comment]
We have a similar issue. Everything installs fine on our machines (running OS X Yosemite). But in our CI npm install fails with the following log

```
18:05:02 > fidonet-mailer-binkp-crypt@0.0.32 install /var/lib/jenkins/workspace/PROJECT/youniverse-application-war/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
18:05:02 > node-gyp configure build
18:05:02 
18:05:03 make: Entering directory `/var/lib/jenkins/workspace/PROJECT/youniverse-application-war/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build'
18:05:03   CXX(target) Release/obj.target/crypt/crypt.o
18:05:03 make: g++: Command not found
18:05:03 make: *** [Release/obj.target/crypt/crypt.o] Error 127
18:05:03 make: Leaving directory `/var/lib/jenkins/workspace/PROJECT/youniverse-application-war/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build'
18:05:03 gyp ERR! build error 
18:05:03 gyp ERR! stack Error: `make` failed with exit code: 2
18:05:03 gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
18:05:03 gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
18:05:03 gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
18:05:03 gyp ERR! System Linux 3.2.0-60-generic
18:05:03 gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
18:05:03 gyp ERR! cwd /var/lib/jenkins/workspace/PROJECT/youniverse-application-war/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
18:05:03 gyp ERR! node -v v0.10.24
18:05:03 gyp ERR! node-gyp -v v0.12.1
```

They're running Linux

**Comment by askovpen** [comment]
`make: g++: Command not found` - install g++
`Error: Can't find Python executable "python", you can set the PYTHON env variable.` - install python

**Comment by misterbrownlee** [comment]
You are pushing a system dependency change under a semver dot version.  I don't see that as a `backward compatible bugfix`

**Comment by blaiprat** [comment]
I would have appreciated a better solution than just closing this ticket with an `install g++`. The problem comes from poor configuration from the project. Not everybody can depend on changes done in the libraries that does't care enough about stability.

**Comment by misterbrownlee** [comment]
I think I was mistaken and it wasn't the fact that the dependency changed, but an upstream project started requiring this which caused that upstream project to need system tools to compile this.  So not exactly the same thing.
