### ISSUE TITLE
Build failures on systems without `g++`

### ISSUE THREAD

**Issue by misterbrownlee** [askovpen/node-fidonet-mailer-binkp-crypt#7]
Hi -

Your recent updates are breaking our CI server:

```
> fidonet-mailer-binkp-crypt@0.0.29 install /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
> node-gyp configure build

make: Entering directory `/apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build'
  CXX(target) Release/obj.target/crypt/crypt.o
make: g++: Command not found
make: *** [Release/obj.target/crypt/crypt.o] Error 127
make: Leaving directory `/apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/qabasel/tools/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-504.1.3.el6.x86_64
gyp ERR! command "node" "/home/qabasel/tools/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher/node_modules/adm-zip/node_modules/fidonet-mailer-binkp-crypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! fidonet-mailer-binkp-crypt@0.0.29 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fidonet-mailer-binkp-crypt@0.0.29 install script.
npm ERR! This is most likely a problem with the fidonet-mailer-binkp-crypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fidonet-mailer-binkp-crypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-504.1.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-504.1.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html
npm ERR! fstream_path /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/node_modules/coralui-grunt-testrunner/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/active-x-obfuscator/node_modules/zeparser/benchmark.html
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/qabasel/tools/nodejs/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /apps/jenkins/workspace/xBuild_Coral_coralui3-component-TEST/npm-debug.log
npm ERR! not ok code 0
```

Sadly, since `karma-sauce-connect` is typically a dev dependency, this won't usually be covered with an npm-shrinkwrap.  We have a work around, but heads up that not all installs are equal.

**Comment by askovpen** [comment]
this only native module.
